# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57e04f914902a6e3ed036bb0c4ee5314027aef8260e11a246e4b9095fe1bf22b45b6b5ee9161e512b8347f9df26e44f18fe26c3c875f2851ab34357b5367d290

test:
  secret_key_base: b5ea830a6cdc23670d270a76734bc8df9c389db5b6f93329352e4daa9b62ec02f0f9245aaea8019ce4305731cb16bd354aa83248bd7f4c19211e98e374127753

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
